from pydantic import BaseModel, Field

# Define the response schema for the chat endpoint
class ChatResponse(BaseModel):
    """
    Schema for the response from the agent chat endpoint.
    Contains the text generated by Gemini and the URL of the generated audio.
    """
    gemini_text: str = Field(..., example="Hello there! How can I assist you today?")
    audio_url: str = Field(..., example="https://murf-audio-url.com/path/to/audio.mp3")

